$schema: http://json-schema.org/draft-07/schema#
id: config.schema.json
name: Schema for HLA-KIR Imputation Workflow
type: object
properties:
  KIRIMP_PANEL_URL:
    type: string
    default: http://imp.science.unimelb.edu.au/kir/static/kirimp.uk1.snp.info.csv
    description: URL for KIR*IMP imputation 301 SNP panel
  OVERCHAIN_URLS:
    type: object
    description: Dictionary of URLs for different ucsc liftover overchains
    properties:
      HG18:
        type: string
        description: HG18 -> HG19 Overchain
        default: "http://hgdownload.soe.ucsc.edu/goldenPath/hg18/liftOver/hg18ToHg19.over.chain.gz"
      HG17:
        type: string
        description: HG17 -> HG19 Overchain
        default: "https://hgdownload.soe.ucsc.edu/goldenPath/hg17/liftOver/hg17ToHg19.over.chain.gz"
      HG16:
        type: string
        description: HG16 -> HG19 Overchain
        default: https://hgdownload.soe.ucsc.edu/goldenPath/hg16/liftOver/hg16ToHg19.over.chain.gz
  project:
    $ref: "#/definitions/project"
    description: Contains settings for a specific run
definitions:
  project:
    type: object
    patternProperties:
      "^[^\./]+$":
        liftover:
          $ref: "#/definitions/liftover"
          description: settings for conversion of data from hg16/hg17/hg18 --> hg19
  liftover:
    type: object
    properties:
        reference:
          type: string
          enum:
            - HG18
            - HG17
            - HG16
          default: HG18
        plink:
          type: string
          pattern: ".+(bed|fam|bim)$"
          description: Path to either bed/bim/fam plink file
        vcf:
          type: string
          pattern: ".+(vcf|bcf|vcf.gz)$"
          description: Path to a VCF file in bcf/vcf/vcf.gz format
